apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mariadb
  name: mariadb
spec:
  containers:
  - image: harbor.kakor.ovh/public/mariadb:latest
    name: mariadb
    resources: {}
    env:
      - name: MARIADB_ROOT_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: mariadb-secret
            key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
