---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    pod: nginx
spec:
  containers:
  - name: nginx
    image: harbor.kakor.ovh/public/nginx:latest
    securityContext:
      allowPrivilegeEscalation: true
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    pod: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80