apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    pod: nginx
spec:
  containers:
  - name: nginx
    image: harbor.kakor.ovh/public/nginx:latest
    securityContext:
      allowPrivilegeEscalation: true
    ports:
    - containerPort: 80
    volumeMounts:
      - name: index
        mountPath: "/usr/share/nginx/html"
        readOnly: true
  volumes:
  # You set volumes at the Pod level, then mount them into containers inside that Pod
  - name: index
    configMap:
      name: canard-website