apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    pod: nginx
spec:
  containers:
  - name: nginx
    image: harbor.kakor.ovh/public/nginx:latest
    env:
        - name: demoenv
          valueFrom:
            configMapKeyRef:
              name: env-demo          # The ConfigMap this value comes from.
              key: demo
    securityContext:
      allowPrivilegeEscalation: true
    ports:
    - containerPort: 80