apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
  - name: httpd
    image: harbor.kakor.ovh/public/httpd:latest
    securityContext:
      allowPrivilegeEscalation: true
    ports:
    - containerPort: 80
